"""init

Revision ID: 6b991877b6f3
Revises: 
Create Date: 2026-01-27 04:33:42.490349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b991877b6f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy_type', sa.Enum('Solar', 'Wind', 'NaturalGas', 'Nuclear', 'Coal', 'Hydro', name='energytype'), nullable=False),
    sa.Column('quantity_mwh', sa.Integer(), nullable=False),
    sa.Column('price_per_mwh', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_start', sa.Date(), nullable=False),
    sa.Column('delivery_end', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Reserved', 'Sold', name='contractstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_delivery_end'), 'contracts', ['delivery_end'], unique=False)
    op.create_index(op.f('ix_contracts_delivery_start'), 'contracts', ['delivery_start'], unique=False)
    op.create_index(op.f('ix_contracts_energy_type'), 'contracts', ['energy_type'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_location'), 'contracts', ['location'], unique=False)
    op.create_index(op.f('ix_contracts_price_per_mwh'), 'contracts', ['price_per_mwh'], unique=False)
    op.create_index(op.f('ix_contracts_quantity_mwh'), 'contracts', ['quantity_mwh'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contract_id', name='uq_user_contract')
    )
    op.create_index(op.f('ix_portfolio_items_contract_id'), 'portfolio_items', ['contract_id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_items_user_id'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_contract_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_quantity_mwh'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_price_per_mwh'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_location'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_energy_type'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_delivery_start'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_delivery_end'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
